In [153]:
import numpy as np
import matplotlib.pyplot as plt

In [154]:
b = np.array([[-3],[-3],[8],[9]])
u1 = [3,1,0,1]
u2 = [1,2,1,1]
u3 = [-1,0,2,-1]

In [155]:
Atrans = np.array([u1,u2,u3])
A= Atrans.T
A


array([[ 3,  1, -1],
       [ 1,  2,  0],
       [ 0,  1,  2],
       [ 1,  1, -1]])

In [156]:
prod1= np.dot(Atrans,A)
prod2= Atrans@b
x= np.linalg.solve(prod1,prod2)
x

array([[-1.],
       [ 2.],
       [ 1.]])

In [157]:
pw = A@x
pw

array([[-2.0000000e+00],
       [ 3.0000000e+00],
       [ 4.0000000e+00],
       [-4.4408921e-16]])

In [158]:
b_ = np.array([-3,-3,8,9])
v1 = np.array([3,1,0,1])
v2 = np.array([1,2,1,1])
v3 = np.array([-1,0,2,-1])

In [159]:
u1= v1
u2= v2 - (np.dot(v2,u1)/np.dot(u1,u1))*u1
u3= v3 - (np.dot(v3,u2)/np.dot(u2,u2))*u2 - (np.dot(v3,u1)/np.dot(u1,u1))*u1

u=np.dot(u3,u2)
u

0.0

In [160]:
nor1= np.linalg.norm(u1)
nor2= np.linalg.norm(u2)
nor3= np.linalg.norm(u3)

In [161]:
n1 = u1/nor1
n2 = u2/nor2
n3 = u3/nor3

In [162]:
print(n1,n2,n3)

[0.90453403 0.30151134 0.         0.30151134] [-0.32961713  0.75341057  0.51796977  0.2354408 ] [ 0.25633581 -0.26982716  0.78249877 -0.49918025]


In [163]:
c1 = np.dot(b_,n1)
c2 = np.dot(b_,n2)
c3 = np.dot(b_,n3)

In [164]:
pw2= c1*n1 + c2*n2 + c3*n3
pw2

array([-2.00000000e+00,  3.00000000e+00,  4.00000000e+00, -1.11022302e-16])